name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jma35507/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jma35507/react-test npm test
 
      - run: docker build -t jma35507/multi-client-2026 ./client
      - run: docker build -t jma35507/multi-nginx-2026 ./nginx
      - run: docker build -t jma35507/multi-server-2026 ./server
      - run: docker build -t jma35507/multi-worker-2026 ./worker

      - run: docker push jma35507/multi-client-2026
      - run: docker push jma35507/multi-nginx-2026
      - run: docker push jma35507/multi-server-2026
      - run: docker push jma35507/multi-worker-2026

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-jm
          environment_name: Multijm-env
          existing_bucket_name: elasticbeanstalk-us-east-1-216989102990
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
